
#ifndef SPI_SPI_CONFIG_H_
#define SPI_SPI_CONFIG_H_

/*
 * select SPI_ENABLE or SPI_DISABLE
 */
#define SPI           SPI_ENABLE

/*
 * select MASTER_SPI_MODE or SLAVE_SPI_MODE
 */
#define SPI_MODE    MASTER_SPI_MODE


/*
 * select
 * RISING_LEADING_EDGE_FALLING_TRAILING_EDGE or
 * FALLING_LEADING_EDGE_RISING_TRAILING_EDGE
 */
#define CLOCK_POLARITY   RISING_LEADING_EDGE_FALLING_TRAILING_EDGE

/*
 * select SAMPLE_LEADING_EDGE_SETUP_TRAILING_EDGE
 * or
 * SETUP_LEADING_EDGE_SAMPLE_TRAILING_EDGE
 */
#define CLOCK_PHASE      SAMPLE_LEADING_EDGE_SETUP_TRAILING_EDGE

/*
 * select the clock rate
 */
#define CLOCK_RATE    DIVIDE_BY_4



#endif /* SPI_SPI_CONFIG_H_ */
